
- name: Access some $evm.root variables
  hosts: all
  connection: local

  vars:
  - manageiq_validate_certs: false

  roles:
- manageiq-core.manageiq-automate

  tasks:
  - name: "Get $evm.root['dialog_value']"
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_attribute:
        object: "root"
        attribute: "dialog_value"
    register: dialog_value

  - set_fact:
        instance_id: "{{ dialog_value }}"

    - name: Add the PowerOff tag
      ec2_tag:
        region: us-east-1
        resource: "{{ dialog_value }}"
        tags:
          PowerOff: false
        state: present
